const colors = ["green", "red", "yellow", "blue"];
let gamePattern = []; // Stores sequence generated by game
let userClickedPattern = []; // Stores sequence clicked by user
let gameActive = false;
let level = 0;

// ✅ Detect event type (mobile vs desktop)
const startEvent = ("ontouchstart" in window) ? "touchstart" : "keydown";
const clickEvent = ("ontouchstart" in window) ? "touchstart" : "click";

// --- Start Game ---
$(document).on(startEvent, function () {
  if (!gameActive) {
    level = 0;
    gamePattern = [];
    $("#level-title").text("Level " + level);
    gameActive = true;
    nextSequence();
  }
});

// --- Player Click/Tap ---
$(".btn").on(clickEvent, function (e) {
  e.preventDefault(); // prevent ghost clicks on mobile

  if (!gameActive) return;

  const userChosenColor = $(this).attr("id");
  userClickedPattern.push(userChosenColor);

  playSound(userChosenColor);
  animatePress(userChosenColor);

  checkAnswer(userClickedPattern.length - 1);
});

// --- Helper Functions ---

function nextSequence() {
  userClickedPattern = [];
  level++;
  $("#level-title").text("Level " + level);

  const randomIndex = Math.floor(Math.random() * colors.length);
  const randomChosenColor = colors[randomIndex];
  gamePattern.push(randomChosenColor);

  $("#" + randomChosenColor)
    .fadeIn(100)
    .fadeOut(100)
    .fadeIn(100);

  playSound(randomChosenColor);
  console.log("Game Pattern:", gamePattern);
}

function checkAnswer(currentLevel) {
  if (userClickedPattern[currentLevel] === gamePattern[currentLevel]) {
    if (userClickedPattern.length === gamePattern.length) {
      setTimeout(nextSequence, 1000);
    }
  } else {
    $("#level-title").text("Game Over! Tap/Press Any Key to Restart");
    playSound("wrong");
    gameActive = false;
    level = 0;
    gamePattern = [];
  }
}

function playSound(name) {
  const audio = new Audio("sounds/" + name + ".mp3");
  audio.play().catch(err => console.log("Sound blocked until user interaction:", err));
}

function animatePress(color) {
  $("#" + color).addClass("pressed");
  setTimeout(() => $("#" + color).removeClass("pressed"), 100);
}
